# 10.14 required for some C++17 features used in TBB
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.14"                # [osx and x86_64]

# Build only for CUDA 11.2+
cuda_compiler_version_min:
  - None  # [not (linux64 or ppc64le or aarch64)]
  - 12.0  # [linux64 or ppc64le or aarch64]
