# 10.14 required for some C++17 features used in TBB
c_stdlib_version:          # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.14"                # [osx and x86_64]

# Build only for CUDA 11.2+
cuda_compiler_version_min:
  - None                       # [osx]
  - 11.2                       # [linux64 or win]
  - 11.2                       # [linux and (ppc64le or aarch64)]
