{% set processor = "cpu" %}
{% set name = "hoomd" %}
{% set version = "4.8.2" %}
{% set build = 0 %}
{% set sha256 = "77b8d947cad99daf2b3ea977b32431bfc854db109be86fd404fe3f0c8e28c6c1" %}
{% set processor = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux64]
{% set processor = "cpu" %}  # [not linux64]


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/hoomd-blue/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-python-site-dir.patch

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage('hoomd', max_pin='x.x.x') }}
  # Upstream package does not support Windows, Python < 3.6, or PyPy
  skip: true  # [win or py<=38 or python_impl == "pypy"]
  skip: true  # [cuda_compiler_version != "None" and  float(cuda_compiler_version) < float(cuda_compiler_version_min)]
  string: {{ processor }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}
  script: bash ${RECIPE_DIR}/build_hoomd.sh gpu  # [linux64 and cuda_compiler_version != "None"]
  script: bash ${RECIPE_DIR}/build_hoomd.sh  # [not linux64 or cuda_compiler_version == "None"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11 >=2.12.0                      # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    # MacOS cross compilation support requires CMake 3.15 or newer
    # 3.23.0 is broken for CUDA builds
    - cmake >=3.16.0,!=3.23.0
    - ninja
    - pkg-config

  host:
    - eigen
    - numpy
    - pybind11 >=2.12.0
    - python
    - tbb
    - tbb-devel
    - pybind11-abi
    # CUDA dependencies
    - cuda-version {{ cuda_compiler_version }}  # [linux64 and cuda_compiler_version != "None"]
    - cuda-cudart-dev  # [linux64 and cuda_compiler_version != "None" and float(cuda_compiler_version) >= 12.0]
    - cuda-driver-dev  # [linux64 and cuda_compiler_version != "None" and float(cuda_compiler_version) >= 12.0]
    - cuda-nvrtc-dev  # [linux64 and cuda_compiler_version != "None" and float(cuda_compiler_version) >= 12.0]
    - cuda-profiler-api  # [linux64 and cuda_compiler_version != "None" and float(cuda_compiler_version) >= 12.0]
    - libcublas-dev  # [linux64 and cuda_compiler_version != "None" and float(cuda_compiler_version) >= 12.0]
    - libcufft-dev  # [linux64 and cuda_compiler_version != "None" and float(cuda_compiler_version) >= 12.0]
    - libcusolver-dev  # [linux64 and cuda_compiler_version != "None" and float(cuda_compiler_version) >= 12.0]
    - libcusparse-dev  # [linux64 and cuda_compiler_version != "None" and float(cuda_compiler_version) >= 12.0]

  run:
    - __cuda >={{ cuda_compiler_version }}  # [linux64 and cuda_compiler_version != "None"]
    - python
    - tbb
    - {{ pin_compatible("cuda-version", max_pin="x", min_pin="x") }}  # [linux64 and cuda_compiler_version != "None"]

test:
  requires:
    - pytest
    - rowan
  imports:
    - hoomd
    - hoomd.md
    - hoomd.hpmc
  commands:
    - pytest --pyargs hoomd -v

about:
  home: https://glotzerlab.engin.umich.edu/hoomd-blue/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: HOOMD-blue is a general-purpose particle simulation toolkit.

  description: |
    HOOMD-blue is a general-purpose particle simulation toolkit, implementing molecular
    dynamics and hard particle Monte Carlo optimized for fast execution on both GPUs and
    CPUs. As a Python package, HOOMD-blue gives you the flexibility to create custom
    initialization routines, control simulation parameters, perform in situ analysis,
    use interactive notebooks, and more.

  doc_url: https://hoomd-blue.readthedocs.io
  dev_url: https://github.com/glotzerlab/hoomd-blue/

extra:
  recipe-maintainers:
    - joaander
    - bdice
    - tcmoore3
