{% set name = "hoomd" %}
{% set version = "2.9.3" %}
{% set build = 0 %}
{% set sha256 = "f714dded7a2e73cf5ecb3b9c2f0b0635a1a0640b7fb368a23a2f8849984e4f69" %}
{% set processor = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux64]
{% set processor = "cpu" %}  # [not linux64]


package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/hoomd-blue/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  # upstream package does not support windows or py27
  skip: true  # [win or py27]
  string: "{{ processor }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  script: "bash ${RECIPE_DIR}/build_hoomd.sh gpu"  # [linux64 and cuda_compiler_version != "None"]
  script: "bash ${RECIPE_DIR}/build_hoomd.sh"  # [not linux64 or cuda_compiler_version == "None"]

  rpaths:
    - lib/
    - lib/python3.8/site-packages/{{ name }}  # [py38]
    - lib/python3.7/site-packages/{{ name }}  # [py37]
    - lib/python3.6/site-packages/{{ name }}  # [py36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    - cmake
    - pkg-config
    - ninja

  host:
    - python
    - numpy
    - tbb-devel
    - tbb

  run:
    - python
    - numpy
    - tbb

test:
  imports:
  - hoomd
  - hoomd.md
  - hoomd.hpmc

about:
  home: https://glotzerlab.engin.umich.edu/hoomd-blue/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'HOOMD-blue is a general-purpose particle simulation toolkit.'

  description: |
    You define particle initial conditions and interactions in a high-level python script. Then tell HOOMD-blue how you want
    to execute the job and it takes care of the rest. Python job scripts give you unlimited flexibility to create custom
    initialization routines, control simulation parameters, and perform in situ analysis.
  doc_url: https://hoomd-blue.readthedocs.io
  dev_url: https://github.com/glotzerlab/hoomd-blue/

extra:
  recipe-maintainers:
    - joaander
    - bdice
