{% set processor = "cpu" %}
{% set name = "hoomd" %}
{% set version = "4.0.1" %}
{% set build = 1 %}
{% set sha256 = "b63dd8debb96f9c530983bd54ecbafa8fd07e017ded3ea64604cfb1f41a644b8" %}
{% set processor = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux64]
{% set processor = "cpu" %}  # [not linux64]


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/hoomd-blue/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  # Upstream package does not support Windows, Python < 3.6, or PyPy
  skip: true  # [win or py<36 or python_impl == "pypy"]
  skip: true  # [cuda_compiler_version != "None" and  float(cuda_compiler_version) < float(cuda_compiler_version_min)]
  string: {{ processor }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}
  script: bash ${RECIPE_DIR}/build_hoomd.sh gpu  # [linux64 and cuda_compiler_version != "None"]
  script: bash ${RECIPE_DIR}/build_hoomd.sh  # [not linux64 or cuda_compiler_version == "None"]

  rpaths:
    - lib/
    - lib/python3.11/site-packages/{{ name }}  # [py==311]
    - lib/python3.10/site-packages/{{ name }}  # [py==310]
    - lib/python3.9/site-packages/{{ name }}  # [py==39]
    - lib/python3.8/site-packages/{{ name }}  # [py==38]
    - lib/python3.7/site-packages/{{ name }}  # [py==37]
    - lib/python3.6/site-packages/{{ name }}  # [py==36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    # MacOS cross compilation support requires CMake 3.15 or newer
    # 3.23.0 is broken for CUDA builds
    - cmake >=3.16.0,!=3.23.0
    - ninja
    - pkg-config

  host:
    - eigen
    - numpy
    - pybind11
    - python
    - tbb
    - tbb-devel
    - pybind11-abi
    # Pin LLVM and clang packages to that pinned by the `compilers` package.
    # This ensures that HOOMD can find the corresponding header files which
    # conda installs to version specific directories.
    - llvmdev 14.0.6
    - clangdev 14.0.6

  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - __cuda >={{ cuda_compiler_version }}  # [linux64 and cuda_compiler_version != "None"]
    - python
    - numpy
    - tbb
    - libstdcxx-devel_linux-64  # [linux64]
    - sysroot_linux-64  # [linux64]
    - libcxx
    - libclang-cpp 14.0.6
    - clang 14.0.6
    - clangxx 14.0.6

test:
  requires:
    - pytest
    - rowan
  imports:
    - hoomd
    - hoomd.md
    - hoomd.hpmc
  commands:
    - pytest --pyargs hoomd -v

about:
  home: https://glotzerlab.engin.umich.edu/hoomd-blue/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: HOOMD-blue is a general-purpose particle simulation toolkit.

  description: |
    HOOMD-blue is a general-purpose particle simulation toolkit, implementing molecular
    dynamics and hard particle Monte Carlo optimized for fast execution on both GPUs and
    CPUs. As a Python package, HOOMD-blue gives you the flexibility to create custom
    initialization routines, control simulation parameters, perform in situ analysis,
    use interactive notebooks, and more.

  doc_url: https://hoomd-blue.readthedocs.io
  dev_url: https://github.com/glotzerlab/hoomd-blue/

extra:
  recipe-maintainers:
    - joaander
    - bdice
    - b-butler
