{% set name = "hoomd" %}
{% set version = "2.4.1" %}
{% set sha256 = "0763c0f701f70439667256b67581b70052877330006cadd7b4eae7655fc913e9" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  # upstream package does not support windows
  skip: true  # [win]

  rpaths:
    - lib/
    - lib/python3.6/site-packages/{{ name }}  # [py36]
    - lib/python3.5/site-packages/{{ name }}  # [py35]
    - lib/python3.4/site-packages/{{ name }}  # [py34]
    - lib/python3.3/site-packages/{{ name }}  # [py33]
    - lib/python2.7/site-packages/{{ name }}  # [py27]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja

  host:
    - python
    - numpy
    - llvmdev
    - clangdev
    - tbb-devel
    - tbb
    - libcxx

  run:
    - python
    - numpy
    - llvmdev
    - clangdev
    - tbb
    - libcxx

test:
  imports:
  - hoomd
  - hoomd.md
  - hoomd.hpmc

about:
  home: http://glotzerlab.engin.umich.edu/hoomd-blue/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'HOOMD-blue is a general-purpose particle simulation toolkit.'

  description: |
    You define particle initial conditions and interactions in a high-level python script. Then tell HOOMD-blue how you want
    to execute the job and it takes care of the rest. Python job scripts give you unlimited flexibility to create custom
    initialization routines, control simulation parameters, and perform in situ analysis.
  doc_url: https://hoomd-blue.readthedocs.io
  dev_url: https://bitbucket.org/glotzer/{{ name }}

extra:
  recipe-maintainers:
    - joaander
