travis:
  secure:
    BINSTAR_TOKEN: LckLqwPTAGZprvfHWWvFp25OCujhqfagKYrqeJwW9ZHkXRak4+L3Y1U9cCDdUg2dwYaXYlCQCvJ0OiSHeMrY4Od1Rg0lchdPzMd4ANn4w/OTAlddHBSMhZoPbZArGDfF4fGyEiFSHW367XUesk58R4GImfSsccpTIGhh73EmJZF1hEWa3ThjmMbJy1j4buFvm8dgR1DVNPsSKwJyNW81l3boo+FQ39m2DUcScabqcE4whUZqVsnHeLa4qCOEPY7MbYSYViGFX7609AM+AahP+GCiQVjZf5YdTLd32zhfgPjPzKG0N01TFYJ3kZM9rb7WYuqKWCA1ps8PF13VXeNmE+a86kbQYks5NWLdEoIkUkFeQiZyfFcPQSbpk8pUdRsxNgcPCoJ8/40qrvgkVfcG5hme/JRxZCnShtUWRGDzfbB0aeHwF/BpXnQ2IVnW4B2EFGJYSkzrxFVqWwsM21EMMBujWrzw/GQkRZDrl+0l5AfC9O3VkmEj4q+DAjsEX2/9NTQpGAFNApWriM2FgdAa1/GETw0XI2004rMSKu0Z/vTxdNYKLGy20psqfG+Qnk76tX1g0lOJ88Fo8SO8FIN2MMJj/dShRD/Sq/10f7dZBjY5DLhrec9y4+kLd/0ZIhU8pxB/6TcOeBbZ+VVWI0ZmY4ZMKA/gHImoMoyZAk+AxCI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
